imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [QaSystemCoreBundle, 'MopaBootstrapBundle']
    #java: /usr/bin/java
    filters:
        less:
            node:       %assetic_node_bin%
            node_paths: %assetic_node_path%
            apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

monolog:
    handlers:
        deamon:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%-daemon.log
            level: info

mopa_bootstrap:
    form: ~
    menu: ~
    icons:
        icon_set: glyphicons
        shortcut: icon

old_sound_rabbit_mq:
    connections:
        default:
            host:      '127.0.0.1'
            port:      5672
            user:      'guest'
            password:  'guest'
            vhost:     '/'
            lazy:      false
    producers:
        project_checkout:
            connection: default
            exchange_options: {name: 'project-checkout', type: direct}
        project_deploy:
            connection: default
            exchange_options: {name: 'project-deploy', type: direct}
        project_pull:
            connection: default
            exchange_options: {name: 'project-pull', type: direct}
    consumers:
        project_checkout:
            connection: default
            exchange_options: {name: 'project-checkout', type: direct}
            queue_options:    {name: 'project-checkout'}
            callback:         project_checkout
        project_deploy:
            connection: default
            exchange_options: {name: 'project-deploy', type: direct}
            queue_options:    {name: 'project-deploy'}
            callback:         project_deploy
        project_pull:
            connection: default
            exchange_options: {name: 'project-pull', type: direct}
            queue_options:    {name: 'project-pull'}
            callback:         project_pull

services:
  project_checkout:
      class:     QaSystem\CoreBundle\Consumer\ProjectCheckoutConsumer
      arguments: ["%kernel.root_dir%", "@logger"]
      tags:
        - { name: monolog.logger, channel: daemon }
  project_deploy:
      class:     QaSystem\CoreBundle\Consumer\ProjectDeployConsumer
      arguments: ["%kernel.root_dir%", "@logger"]
      tags:
        - { name: monolog.logger, channel: daemon }
  project_pull:
      class:     QaSystem\CoreBundle\Consumer\ProjectPullConsumer
      arguments: ["%kernel.root_dir%", "@logger"]
      tags:
        - { name: monolog.logger, channel: daemon }
  deployment_tool:
      class:     QaSystem\CoreBundle\Service\DeploymentTool
      arguments: ["@doctrine.orm.entity_manager", "@logger"]
      tags:
        - { name: monolog.logger, channel: daemon }
